### ISSUE TITLE
能否写一下ts支持

### ISSUE THREAD

**Issue by mashedpotato2018** [hash-bang/tree-tools#3]
interface treeToolConfig {
    id: any,
    children: string,
    pid: string
  }
  interface treeToolNode {

  }
  type treeToolCallcack = (node:any)=>boolean
  type treeToolMethod = (tree:any[],callback: treeToolCallcack)=> treeToolNode
  type treeToolMethodVoid = (tree:any[],callback: treeToolCallcack)=> void
  interface treeTool{
    createInstance:(config:treeToolConfig) => treeTool,
    // 列表结构转树 使用instance option可以不传
    fromList:(data:any[],option?:treeToolConfig)=> any[],
    // 树结构转列表结构
    toList:(tree:any[])=>any[],
    // 查找节点
    findNode:treeToolMethod,
    // 查找符合条件的所有节点
    findNodeAll:treeToolMethod,
    // 查找节点路径
    findPath:treeToolMethod,
    // 查找符合条件的所有节点的路径
    findPathAll:treeToolMethod,
    // 树节点过滤
    filter:treeToolMethod,
    // 树节点遍历 深度优先
    forEach:treeToolMethodVoid,
    // 节点插入：在node前插入newNode
    insertBefore:(tree:any[],newNode:treeToolNode,node:treeToolNode)=> void
    // 节点插入：在node后插入newNode
    insertAfter:(tree:any[],newNode:treeToolNode,node:treeToolNode)=> void
    // 节点删除：删除符合条件的Node
    removeNode: treeToolMethodVoid
  }

**Comment by hash-bang** [comment]
Hi there,

Sorry my native language isn't Chinese.

Could I get a quick summary of what you are asking here?

**Comment by mashedpotato2018** [comment]
can write typeScript?
vscode can not IntelliSense

**Comment by hash-bang** [comment]
Sorry but I'm unfamiliar with TypeScript.

If you wish to write the bindings or function documentation yourself though I'll happily accept it as a PR.
